import mongoose from 'mongoose'
import Category from '../model/Category.js'
import { connectDb } from '../config/db.js'
import 'dotenv/config'

const seedCategories = async () => {
  try {
    await connectDb()
    
    const categories = [
      { name: 'Fashion', description: 'Fashion and clothing items' },
      { name: 'Electronics', description: 'Electronic devices and gadgets' },
      { name: 'Jewelry', description: 'Jewelry and accessories' },
      { name: 'Home', description: 'Home and living products' }
    ]

    // Check if categories already exist
    const existingCount = await Category.countDocuments()
    
    console.log(`Found ${existingCount} existing categories`)
    
    // Add missing categories one by one
    for (const cat of categories) {
      const exists = await Category.findOne({ name: cat.name })
      if (!exists) {
        // Create category with slug
        const newCat = new Category(cat)
        // Slug will be auto-generated by the pre-save hook
        await newCat.save()
        console.log(`✅ Created category: ${cat.name} (slug: ${newCat.slug})`)
      } else {
        // Update existing category to ensure it has a slug
        if (!exists.slug) {
          exists.slug = exists.name.toLowerCase().replace(/\s+/g, '-')
          await exists.save()
          console.log(`✅ Updated category slug: ${exists.name} -> ${exists.slug}`)
        } else {
          console.log(`⏭️  Category already exists: ${cat.name}`)
        }
      }
    }

    const allCategories = await Category.find()
    console.log('\n📋 All Categories:')
    allCategories.forEach(cat => {
      console.log(`  - ${cat.name} (${cat.slug})`)
    })

    process.exit(0)
  } catch (error) {
    console.error('❌ Error seeding categories:', error)
    process.exit(1)
  }
}

seedCategories()

